# Generated by Django 5.1.7 on 2025-03-25 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time_of_call', models.TimeField()),
                ('details', models.CharField(max_length=200)),
                ('caller', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contact_number', models.IntegerField()),
                ('action_taken', models.CharField(max_length=200)),
                ('time_of_dispatch', models.TimeField()),
                ('responded_by', models.CharField(max_length=100)),
                ('back_to_base', models.TimeField()),
                ('radio_or_telephone', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
            ],
        ),
    ]
